### ISSUE TITLE
Goo.gl no longer works

### ISSUE THREAD

**Issue by kongd** [hzlzh/Alfred-Workflows#10]
Goo.gl no longer shortens links properly - I get nothing in my clipboard.

**Comment by hzlzh** [comment]
@kongd Google changed its api, I'll adjust it soon.

**Comment by ddarbyson** [comment]
Yup, Google isn't working.

**Comment by ddarbyson** [comment]
...is there anybody out there?

**Comment by chevex** [comment]
+1

**Comment by chevex** [comment]
I believe this is because the API now has usage restrictions. @hzlzh needs to register the app with the Google API and get a token to send along with API requests.

![image](https://cloud.githubusercontent.com/assets/874394/7459564/35557b80-f25a-11e4-83ad-b1a6975bf58d.png)

**Comment by chevex** [comment]
I took the liberty of registering an app with the Google API Console on my own account and changed the source appropriately on my fork of this repo. Anyone who wants it can download the updated workflow here: [goo.gl fix](https://github.com/chevex/Alfred-Workflows/raw/master/Downloads/Shorten-URL.alfredworkflow).

This is temporary until @hzlzh is able to get to it :)

**Comment by sarkis** [comment]
@hzlzh I also did what @chevex mentioned above. What I needed to do is update the api url here: https://github.com/hzlzh/Alfred-Workflows/blob/master/Shorten-URL/shorten_url.py#L19

and add ?key=(google_api_key)

**Comment by sarkis** [comment]
@chevex I found your comment after I already did the same as you :)

:+1: for the work around and detailed explanation

**Comment by ddarbyson** [comment]
thanks @chevex for the explanation on how to fix this broken API, your fix works.

**Comment by maxrothman** [comment]
Still broken, if it's not going to be fixed (or if the author doesn't want to register an app to use by default) please just remove the goo.gl option.

**Comment by chevex** [comment]
I don't want to step on any toes but I'm happy to take over this project if the author isn't interested any longer.

**Comment by littke** [comment]
@hzlzh Did you see that you got an offer for a new maintainer for this project? ^

**Comment by chevex** [comment]
And I'm still open to maintaining it :)

**Comment by hzlzh** [comment]
@littke @chevex That's cool, you can send pull request to this repo or I can add you as maintainers if you like?

**Comment by chevex** [comment]
I would have sent a PR but I generated my own token and figured you would want to do the same for Google yourself. I suppose it probably doesn't matter either way. I can submit a PR with my token in it

**Comment by chevex** [comment]
I also would not mind being added as a maintainer and I'm happy to keep things up-to-date :-)

**Comment by chevex** [comment]
Sorry, I apparently did not see the notification for your comment but only for the closing of the issue

**Comment by hzlzh** [comment]
A PR would be best, also you can add your googl token in the workflow, thanks for your support. :)
