### ISSUE TITLE
many shorten service is unavailable

### ISSUE THREAD

**Issue by young001** [hzlzh/Alfred-Workflows#11]
t.cn has rate limit,so if we use the common key,it will be unavailable when reach the limit,I suggest u can add baidu shorten url service: http://help.baidu.com/question?prod_en=webmaster&class=%CD%F8%D2%B3%CB%D1%CB%F7%CC%D8%C9%AB%B9%A6%C4%DC&id=1000913#05

**Comment by hzlzh** [comment]
got it  thanks

**Comment by hzlzh** [comment]
@young001 `t.cn` API is now fixed without any limit in the future. Try it here:
https://github.com/hzlzh/Alfred-Workflows/raw/master/Downloads/Shorten-URL.alfredworkflow
