### ISSUE TITLE
Update github shorten service url to "https://git.io"

### ISSUE THREAD

**Issue by cgjosephlee** [hzlzh/Alfred-Workflows#23]
The old "http://git.io" is no longer available and returning errors.

**Comment by AlexWang-16** [comment]
Hi @cgjosephlee can you please provide step-by-step instructions to reproduce the problem?

I tried it just now and my experience was that git.io does not work at all. Alfred notification shows that it has been copied to clipboard, but when I paste, the original link is showing.

![issue_23](https://user-images.githubusercontent.com/13398997/37885006-dfd51d24-3080-11e8-8291-26985dab6940.gif)

**Comment by cgjosephlee** [comment]
@AlexWang-16 Simply update the url in this line to "https://git.io", the "http://" one is deprecated.
![2018-03-27 12 06 30](https://user-images.githubusercontent.com/12654602/37946383-a692aa6c-31b7-11e8-9d39-c13c36ea1069.png)
