### ISSUE TITLE
Use own bitly API key to track clicks?

### ISSUE THREAD

**Issue by jamesmills** [hzlzh/Alfred-Workflows#4]
Can you set it to use your own bitly API key so that I can monitor clicks?

**Comment by cfdynamics** [comment]
Bump - exactly what I'd like to do.  Please add this feature.  Thanks!

**Comment by cfdynamics** [comment]
Gave me an idea - looked closer and it's all there - open the script filter of the workflow and you'll see login and apikey variables for bit.ly.  I edited it, adding my own and it worked like a charm!  Easy peasy!  Good luck @jamesmills

**Comment by hzlzh** [comment]
Nice work :+1:

**Comment by jamesmills** [comment]
Awesome. Thanks @cfdynamics
