### ISSUE TITLE
Unable to run task!

### ISSUE THREAD

**Issue by VincentSit** [hzlzh/Alfred-Workflows#9]
Mac 10.10.2
Alfred v2.5.1(308)

当输入 `translate ` 后，键入任何字符就弹出此提示框，稍微 google 了下没找到有类似的案例。请问如何解决？

![c2888b6e-cc27-4bb3-895f-e1e474525109](https://cloud.githubusercontent.com/assets/4084679/5629579/2d9e4cd0-95f0-11e4-8126-06c679a9aa3e.png)

**Comment by VincentSit** [comment]
抱歉发错 repo.

**Comment by hzlzh** [comment]
:) 如果是 workflow 的使用问题，可以反馈到对于的作者 `release homepage`
